import type { MenuItem } from '@/types'

export const menuItems: MenuItem[] = [
  // ── COCKTAILS ─────────────────────────────────────────────
  {
    id: 'c1',
    name: 'Aperol Spritz',
    nameIt: 'Aperol Spritz',
    nameEn: 'Aperol Spritz',
    nameDe: 'Aperol Spritz',
    nameFr: 'Aperol Spritz',
    description: 'Aperol, Prosecco DOC, soda, arancia',
    descriptionIt: 'Aperol, Prosecco DOC, soda, arancia fresca',
    descriptionEn: 'Aperol, Prosecco DOC, soda water, fresh orange',
    descriptionDe: 'Aperol, Prosecco DOC, Soda, frische Orange',
    descriptionFr: 'Aperol, Prosecco DOC, eau gazeuse, orange fraîche',
    price: 8.0,
    category: 'cocktails',
    alcohol: 11,
    tags: ['classico', 'spritz'],
    image: '/images/aperol-spritz.jpg',
  },
  {
    id: 'c2',
    name: 'Negroni',
    nameIt: 'Negroni',
    nameEn: 'Negroni',
    nameDe: 'Negroni',
    nameFr: 'Negroni',
    description: 'Gin, Campari, Vermouth Rosso, arancia',
    descriptionIt: 'Gin London Dry, Campari, Vermouth Rosso, scorzetta d\'arancia',
    descriptionEn: 'London Dry Gin, Campari, Sweet Vermouth, orange peel',
    descriptionDe: 'London Dry Gin, Campari, roter Wermut, Orangenschale',
    descriptionFr: 'Gin London Dry, Campari, Vermouth rouge, zeste d\'orange',
    price: 10.0,
    category: 'cocktails',
    alcohol: 24,
    tags: ['classico', 'stirred'],
    image: '/images/negroni.jpg',
  },
  {
    id: 'c3',
    name: 'Hugo',
    nameIt: 'Hugo',
    nameEn: 'Hugo',
    nameDe: 'Hugo',
    nameFr: 'Hugo',
    description: 'Sciroppo di sambuco, Prosecco, menta, lime',
    descriptionIt: 'Sciroppo di sambuco, Prosecco DOC, menta fresca, lime',
    descriptionEn: 'Elderflower syrup, Prosecco DOC, fresh mint, lime',
    descriptionDe: 'Holunderblütensirup, Prosecco DOC, frische Minze, Limette',
    descriptionFr: 'Sirop de sureau, Prosecco DOC, menthe fraîche, citron vert',
    price: 8.0,
    category: 'cocktails',
    alcohol: 9,
    tags: ['leggero', 'fresco'],
    image: '/images/hugo.jpg',
  },
  {
    id: 'c4',
    name: 'Mojito',
    nameIt: 'Mojito',
    nameEn: 'Mojito',
    nameDe: 'Mojito',
    nameFr: 'Mojito',
    description: 'Rum bianco, lime, zucchero di canna, menta, soda',
    descriptionIt: 'Rum Bianco, lime fresco, zucchero di canna, menta fresca, soda',
    descriptionEn: 'White Rum, fresh lime, cane sugar, fresh mint, soda water',
    descriptionDe: 'Weißer Rum, frische Limette, Rohrzucker, frische Minze, Soda',
    descriptionFr: 'Rhum blanc, citron vert frais, sucre de canne, menthe fraîche, eau gazeuse',
    price: 9.0,
    category: 'cocktails',
    alcohol: 13,
    tags: ['classico', 'fresco'],
  },
  {
    id: 'c5',
    name: 'Bellini',
    nameIt: 'Bellini',
    nameEn: 'Bellini',
    nameDe: 'Bellini',
    nameFr: 'Bellini',
    description: 'Purea di pesca bianca, Prosecco DOC',
    descriptionIt: 'Purea di pesca bianca del Veneto, Prosecco DOC Valdobbiadene',
    descriptionEn: 'White peach purée, Prosecco DOC Valdobbiadene',
    descriptionDe: 'Weißpfirsich-Püree, Prosecco DOC Valdobbiadene',
    descriptionFr: 'Purée de pêche blanche, Prosecco DOC Valdobbiadene',
    price: 9.0,
    category: 'cocktails',
    alcohol: 8,
    tags: ['veneziano', 'prosecco'],
  },
  {
    id: 'c6',
    name: 'Cosmopolitan',
    description: 'Vodka citrus, triple sec, succo di mirtillo rosso, lime',
    descriptionEn: 'Citrus vodka, triple sec, cranberry juice, lime',
    descriptionDe: 'Zitrus-Vodka, Triple Sec, Cranberry-Saft, Limette',
    descriptionFr: 'Vodka citrus, triple sec, jus de canneberge, citron vert',
    price: 10.0,
    category: 'cocktails',
    alcohol: 20,
    tags: ['classico', 'city'],
  },
  {
    id: 'c7',
    name: 'Espresso Martini',
    description: 'Vodka, liquore al caffè, espresso, sciroppo semplice',
    descriptionEn: 'Vodka, coffee liqueur, fresh espresso, simple syrup',
    descriptionDe: 'Vodka, Kaffeelikör, frischer Espresso, Zuckersirup',
    descriptionFr: 'Vodka, liqueur de café, espresso frais, sirop simple',
    price: 11.0,
    category: 'cocktails',
    alcohol: 22,
    tags: ['after dinner', 'coffee'],
    image: '/images/espresso-martini.jpg',
  },
  {
    id: 'c8',
    name: 'Americano',
    description: 'Campari, Vermouth Rosso, soda, arancia',
    descriptionEn: 'Campari, Sweet Vermouth, soda water, orange',
    descriptionDe: 'Campari, roter Wermut, Soda, Orange',
    descriptionFr: 'Campari, Vermouth rouge, eau gazeuse, orange',
    price: 8.0,
    category: 'cocktails',
    alcohol: 12,
    tags: ['classico', 'aperitivo'],
  },

  // ── SIGNATURE ─────────────────────────────────────────────
  {
    id: 's1',
    name: 'Wunderbar Special',
    description: 'Il nostro cocktail signature — segreto dello chef',
    descriptionIt: 'Gin artigianale, acqua di fiori, yuzu, prosecco, foglia d\'oro',
    descriptionEn: 'Craft gin, floral water, yuzu, prosecco, gold leaf',
    descriptionDe: 'Handwerksgin, Blütenwasser, Yuzu, Prosecco, Blattgold',
    descriptionFr: 'Gin artisanal, eau florale, yuzu, prosecco, feuille d\'or',
    price: 14.0,
    category: 'signature',
    alcohol: 18,
    tags: ['signature', 'exclusive'],
    isSignature: true,
    isNew: false,
    image: '/images/wunderbar-special.jpg',
  },
  {
    id: 's2',
    name: 'Golden Hour',
    description: 'Rum invecchiato, miele di acacia, limone, ginger beer, polvere d\'oro',
    descriptionEn: 'Aged rum, acacia honey, lemon, ginger beer, gold dust',
    descriptionDe: 'Gereifter Rum, Akazienhonig, Zitrone, Ginger Beer, Goldstaub',
    descriptionFr: 'Rhum vieilli, miel d\'acacia, citron, ginger beer, poudre d\'or',
    price: 13.0,
    category: 'signature',
    alcohol: 16,
    tags: ['signature', 'dorato'],
    isSignature: true,
    image: '/images/golden-hour.jpg',
  },
  {
    id: 's3',
    name: 'Lago di Como',
    description: 'Gin botanico, acqua tonica al bergamotto, cetriolo, lavanda',
    descriptionEn: 'Botanical gin, bergamot tonic, cucumber, lavender',
    descriptionDe: 'Botanischer Gin, Bergamotte-Tonic, Gurke, Lavendel',
    descriptionFr: 'Gin botanique, tonic bergamote, concombre, lavande',
    price: 12.0,
    category: 'signature',
    alcohol: 14,
    tags: ['signature', 'italiano'],
    isSignature: true,
  },
  {
    id: 's4',
    name: 'Milano Sunset',
    description: 'Campari, Aperol, succo di pompelmo rosa, prosecco, rosmarino',
    descriptionEn: 'Campari, Aperol, pink grapefruit juice, prosecco, rosemary',
    descriptionDe: 'Campari, Aperol, rosa Grapefruitsaft, Prosecco, Rosmarin',
    descriptionFr: 'Campari, Aperol, jus de pamplemousse rose, prosecco, romarin',
    price: 12.0,
    category: 'signature',
    alcohol: 13,
    tags: ['signature', 'spritz'],
    isSignature: true,
    isNew: true,
  },

  // ── WINES ─────────────────────────────────────────────────
  {
    id: 'w1',
    name: 'Prosecco DOC',
    description: 'Valdobbiadene — Veneto',
    descriptionEn: 'Glass / Bottle — Valdobbiadene, Veneto',
    price: 6.0,
    category: 'wines',
    tags: ['spumante', 'bianco'],
  },
  {
    id: 'w2',
    name: 'Pinot Grigio DOC',
    description: 'Alto Adige — Kellerei Cantina Terlan',
    price: 7.0,
    category: 'wines',
    tags: ['bianco', 'trentino'],
  },
  {
    id: 'w3',
    name: 'Chianti Classico DOCG',
    description: 'Toscana — Castello di Brolio, Ricasoli',
    price: 8.0,
    category: 'wines',
    tags: ['rosso', 'toscana'],
  },
  {
    id: 'w4',
    name: 'Barolo DOCG',
    description: 'Piemonte — Giacomo Conterno',
    price: 14.0,
    category: 'wines',
    tags: ['rosso', 'piemonte', 'premium'],
  },
  {
    id: 'w5',
    name: 'Brunello di Montalcino DOCG',
    description: 'Toscana — Biondi Santi',
    price: 18.0,
    category: 'wines',
    tags: ['rosso', 'toscana', 'premium'],
  },

  // ── BEERS ─────────────────────────────────────────────────
  {
    id: 'b1',
    name: 'Birra Moretti',
    description: '33cl — Bottiglia',
    price: 4.0,
    category: 'beers',
    tags: ['italiana', 'lager'],
  },
  {
    id: 'b2',
    name: 'Peroni Nastro Azzurro',
    description: '33cl — Bottiglia',
    price: 4.5,
    category: 'beers',
    tags: ['italiana', 'premium'],
  },
  {
    id: 'b3',
    name: 'Birra Artigianale del Giorno',
    description: 'Spillata — chiedere al banco',
    descriptionEn: 'Craft beer on tap — ask the bar',
    descriptionDe: 'Craft-Bier vom Fass — an der Bar erfragen',
    price: 6.0,
    category: 'beers',
    tags: ['artigianale', 'spillata'],
    isNew: true,
  },

  // ── SOFT DRINKS ───────────────────────────────────────────
  {
    id: 'sd1',
    name: 'Acqua Naturale / Frizzante',
    description: 'San Pellegrino / Panna — 75cl',
    price: 3.0,
    category: 'soft',
    tags: ['acqua'],
  },
  {
    id: 'sd2',
    name: 'Coca-Cola',
    description: '33cl — Lattina',
    price: 3.5,
    category: 'soft',
  },
  {
    id: 'sd3',
    name: 'Succo di Frutta',
    description: 'Arancia, Mela, Pesca, Pera',
    descriptionEn: 'Orange, Apple, Peach, Pear',
    price: 3.5,
    category: 'soft',
    tags: ['succo'],
  },
  {
    id: 'sd4',
    name: 'Limonata della Casa',
    description: 'Limoni di Sicilia, menta fresca, zucchero di canna',
    descriptionEn: 'Sicilian lemons, fresh mint, cane sugar',
    price: 5.0,
    category: 'soft',
    tags: ['artigianale', 'fresco'],
    isNew: false,
  },

  // ── PIZZA ─────────────────────────────────────────────────
  {
    id: 'p1',
    name: 'Margherita',
    description: 'Pomodoro San Marzano, Fior di Latte, basilico fresco, EVO',
    descriptionEn: 'San Marzano tomato, Fior di Latte mozzarella, fresh basil, EVOO',
    descriptionDe: 'San Marzano Tomate, Fior di Latte, frisches Basilikum, Olivenöl',
    descriptionFr: 'Tomate San Marzano, Fior di Latte, basilic frais, huile d\'olive',
    price: 10.0,
    category: 'pizza',
    tags: ['classica', 'vegetariana'],
    isVegetarian: true,
    image: '/images/margherita.jpg',
  },
  {
    id: 'p2',
    name: 'Bufala DOP',
    description: 'Pomodoro San Marzano, Mozzarella di Bufala DOP, pomodorini, basilico',
    descriptionEn: 'San Marzano tomato, Buffalo Mozzarella DOP, cherry tomatoes, basil',
    price: 14.0,
    category: 'pizza',
    tags: ['premium', 'vegetariana'],
    isVegetarian: true,
  },
  {
    id: 'p3',
    name: 'Diavola',
    description: 'Pomodoro, Fior di Latte, salame piccante calabrese, peperoncino',
    descriptionEn: 'Tomato, Fior di Latte, spicy Calabrian salami, chilli',
    descriptionDe: 'Tomate, Fior di Latte, scharfe Salami, Peperoncino',
    price: 12.0,
    category: 'pizza',
    tags: ['piccante', 'salumi'],
    isSpicy: true,
  },
  {
    id: 'p4',
    name: 'Quattro Stagioni',
    description: 'Pomodoro, Fior di Latte, prosciutto, funghi, carciofi, olive',
    descriptionEn: 'Tomato, Fior di Latte, ham, mushrooms, artichokes, olives',
    price: 13.0,
    category: 'pizza',
    tags: ['classica'],
  },
  {
    id: 'p5',
    name: 'Prosciutto e Funghi',
    description: 'Pomodoro, Fior di Latte, prosciutto cotto, funghi porcini',
    descriptionEn: 'Tomato, Fior di Latte, cooked ham, porcini mushrooms',
    price: 12.0,
    category: 'pizza',
    tags: ['classica'],
  },
  {
    id: 'p6',
    name: 'Wunderbar Pizza',
    description: 'Crema di tartufo, burrata, prosciutto crudo 24 mesi, rucola, scaglie di Grana',
    descriptionEn: 'Truffle cream, burrata, 24-month Parma ham, rocket, Grana flakes',
    descriptionDe: 'Trüffelcreme, Burrata, 24 Monate Parma-Schinken, Rucola, Grana-Späne',
    price: 18.0,
    category: 'pizza',
    tags: ['signature', 'premium', 'tartufo'],
    isSignature: true,
    image: '/images/wunderbar-pizza.jpg',
  },
  {
    id: 'p7',
    name: 'Capricciosa',
    description: 'Pomodoro, Fior di Latte, prosciutto, funghi, carciofi, uovo',
    price: 12.0,
    category: 'pizza',
    tags: ['classica'],
  },
  {
    id: 'p8',
    name: 'Napoletana',
    description: 'Pomodoro San Marzano, acciughe del Cantabrico, capperi, olive taggiasche',
    descriptionEn: 'San Marzano tomato, Cantabrian anchovies, capers, taggiasca olives',
    price: 13.0,
    category: 'pizza',
    tags: ['pesce'],
  },
  {
    id: 'p9',
    name: 'Tonno e Cipolla',
    description: 'Pomodoro, Fior di Latte, tonno del Mediterraneo, cipolla di Tropea',
    price: 12.0,
    category: 'pizza',
    tags: ['pesce'],
  },
  {
    id: 'p10',
    name: 'Pistacchio e Mortadella',
    description: 'Crema di pistacchio, Fior di Latte, mortadella IGP, granella di pistacchio',
    descriptionEn: 'Pistachio cream, Fior di Latte, IGP mortadella, pistachio crumbs',
    price: 15.0,
    category: 'pizza',
    tags: ['premium', 'tendenza'],
    isNew: true,
  },

  // ── SEAFOOD ───────────────────────────────────────────────
  {
    id: 'sf1',
    name: 'Frittura di Mare',
    description: 'Calamari, gamberi, seppioline, fritte — limone, maionese alla paprica',
    descriptionEn: 'Calamari, prawns, cuttlefish, fried — lemon, paprika mayo',
    price: 18.0,
    category: 'seafood',
    tags: ['fritto'],
  },
  {
    id: 'sf2',
    name: 'Branzino al Sale',
    description: 'Branzino intero al forno in crosta di sale, verdure di stagione, limone',
    descriptionEn: 'Whole sea bass baked in salt crust, seasonal vegetables, lemon',
    price: 26.0,
    category: 'seafood',
    tags: ['forno', 'integrale'],
    image: '/images/branzino.jpg',
  },
  {
    id: 'sf3',
    name: 'Gamberi all\'Aglio e Limone',
    description: 'Gamberi reali saltati in padella, aglio, peperoncino, limone, prezzemolo',
    descriptionEn: 'King prawns pan-fried with garlic, chilli, lemon, parsley',
    price: 22.0,
    category: 'seafood',
    tags: ['padella'],
    isSpicy: true,
  },
  {
    id: 'sf4',
    name: 'Ostriche Fresche',
    description: 'Ostriche N.3 — 6 pezzi, limone, tabasco, pane di segale',
    descriptionEn: 'Fresh Oysters N.3 — 6 pieces, lemon, tabasco, rye bread',
    price: 24.0,
    category: 'seafood',
    tags: ['crudo', 'premium'],
  },
  {
    id: 'sf5',
    name: 'Salmone alla Griglia',
    description: 'Filetto di salmone norvegese, asparagi, salsa al limone e capperi',
    descriptionEn: 'Norwegian salmon fillet, asparagus, lemon caper sauce',
    price: 20.0,
    category: 'seafood',
    tags: ['griglia'],
  },

  // ── MEAT ──────────────────────────────────────────────────
  {
    id: 'm1',
    name: 'Tagliata di Manzo',
    description: 'Controfiletto di Chianina, rucola, pomodorini, scaglie di Grana Padano',
    descriptionEn: 'Chianina striploin, rocket, cherry tomatoes, Grana Padano shavings',
    price: 28.0,
    category: 'meat',
    tags: ['griglia', 'premium'],
    image: '/images/tagliata.jpg',
  },
  {
    id: 'm2',
    name: 'Bistecca alla Fiorentina',
    description: 'T-bone di Chianina IGP, 600g, cotta alla griglia, rosmarino, EVO',
    descriptionEn: 'Chianina IGP T-bone, 600g, wood-grilled, rosemary, EVOO',
    price: 45.0,
    category: 'meat',
    tags: ['griglia', 'premium', 'toscana'],
    isSignature: true,
  },
  {
    id: 'm3',
    name: 'Pollo alla Parmigiana',
    description: 'Petto di pollo impanato, salsa di pomodoro, Fior di Latte, basilico',
    descriptionEn: 'Breaded chicken breast, tomato sauce, Fior di Latte, basil',
    price: 17.0,
    category: 'meat',
    tags: ['classico'],
  },
  {
    id: 'm4',
    name: 'Costolette di Agnello',
    description: 'Costolette d\'agnello in crosta di erbe aromatiche, patate al forno, menta',
    descriptionEn: 'Herb-crusted lamb chops, roasted potatoes, mint jus',
    price: 26.0,
    category: 'meat',
    tags: ['forno', 'premium'],
  },
  {
    id: 'm5',
    name: 'Involtini di Vitello',
    description: 'Vitello farcito con prosciutto e salvia, salsa al marsala, purè',
    descriptionEn: 'Veal stuffed with ham and sage, Marsala sauce, potato purée',
    price: 22.0,
    category: 'meat',
    tags: ['romano'],
  },

  // ── STARTERS ──────────────────────────────────────────────
  {
    id: 'st1',
    name: 'Bruschetta al Pomodoro',
    description: 'Pane grigliato, pomodoro fresco, basilico, aglio, olio EVO',
    descriptionEn: 'Grilled bread, fresh tomato, basil, garlic, EVOO',
    price: 7.0,
    category: 'starters',
    isVegan: true,
    isVegetarian: true,
    tags: ['vegetariano'],
  },
  {
    id: 'st2',
    name: 'Burrata della Puglia',
    description: 'Burrata fresca DOP, pomodorini confit, pesto di basilico, grissini',
    descriptionEn: 'Fresh DOP Burrata, confit cherry tomatoes, basil pesto, breadsticks',
    price: 14.0,
    category: 'starters',
    isVegetarian: true,
    tags: ['premium', 'vegetariano'],
    image: '/images/burrata.jpg',
  },
  {
    id: 'st3',
    name: 'Carpaccio di Manzo',
    description: 'Filetto di manzo affettato finissimo, scaglie di Grana, rucola, limone',
    descriptionEn: 'Paper-thin beef tenderloin, Grana shavings, rocket, lemon dressing',
    price: 16.0,
    category: 'starters',
    tags: ['crudo', 'premium'],
  },
  {
    id: 'st4',
    name: 'Tagliere Misto',
    description: 'Selezione di salumi e formaggi italiani, miele, composte, gnocco fritto',
    descriptionEn: 'Selection of Italian cured meats and cheeses, honey, preserves, fried bread',
    price: 22.0,
    category: 'starters',
    tags: ['condivisione', 'premium'],
  },

  // ── DESSERTS ──────────────────────────────────────────────
  {
    id: 'd1',
    name: 'Tiramisù della Casa',
    description: 'Ricetta originale — savoiardi, mascarpone, espresso, cacao',
    descriptionEn: 'Original recipe — ladyfingers, mascarpone, espresso, cocoa',
    descriptionDe: 'Originalrezept — Löffelbiskuits, Mascarpone, Espresso, Kakao',
    descriptionFr: 'Recette originale — biscuits, mascarpone, espresso, cacao',
    price: 8.0,
    category: 'desserts',
    tags: ['classico', 'italiano'],
    isVegetarian: true,
    image: '/images/tiramisu.jpg',
  },
  {
    id: 'd2',
    name: 'Panna Cotta al Caramello',
    description: 'Panna cotta alla vaniglia, salsa al caramello salato, frutta fresca',
    descriptionEn: 'Vanilla panna cotta, salted caramel sauce, fresh berries',
    price: 7.0,
    category: 'desserts',
    tags: ['classico'],
    isVegetarian: true,
  },
  {
    id: 'd3',
    name: 'Cannoli Siciliani',
    description: 'Cannoli croccanti, ricotta di pecora, pistacchio, scorza d\'arancia candita',
    descriptionEn: 'Crispy cannoli, sheep ricotta, pistachio, candied orange peel',
    price: 8.0,
    category: 'desserts',
    tags: ['siciliano'],
    isVegetarian: true,
  },
  {
    id: 'd4',
    name: 'Fondente al Cioccolato',
    description: 'Tortino caldo al cioccolato fondente, cuore morbido, gelato alla vaniglia',
    descriptionEn: 'Warm dark chocolate fondant, soft centre, vanilla ice cream',
    price: 9.0,
    category: 'desserts',
    tags: ['cioccolato', 'caldo'],
    isVegetarian: true,
    image: '/images/fondente.jpg',
  },
  {
    id: 'd5',
    name: 'Gelato Artigianale',
    description: '3 palline a scelta — nocciola, pistacchio, limone, fragola, cioccolato',
    descriptionEn: '3 scoops of choice — hazelnut, pistachio, lemon, strawberry, chocolate',
    price: 6.0,
    category: 'desserts',
    tags: ['gelato'],
    isVegetarian: true,
  },
  {
    id: 'd6',
    name: 'Affogato al Caffè',
    description: 'Gelato alla crema, doppio espresso caldo, granella di nocciole',
    descriptionEn: 'Cream gelato, double hot espresso, hazelnut crumble',
    price: 7.0,
    category: 'desserts',
    tags: ['caffè', 'gelato'],
    isVegetarian: true,
  },
]

export const menuCategories = [
  { id: 'all',       label: 'Tutto',          labelEn: 'All',         labelDe: 'Alle',      labelFr: 'Tout',        icon: '✦' },
  { id: 'cocktails', label: 'Cocktails',       labelEn: 'Cocktails',   labelDe: 'Cocktails', labelFr: 'Cocktails',   icon: '🍸' },
  { id: 'signature', label: 'Signature',       labelEn: 'Signature',   labelDe: 'Signature', labelFr: 'Signature',   icon: '✦' },
  { id: 'wines',     label: 'Vini',            labelEn: 'Wines',       labelDe: 'Weine',     labelFr: 'Vins',        icon: '🍷' },
  { id: 'beers',     label: 'Birre',           labelEn: 'Beers',       labelDe: 'Biere',     labelFr: 'Bières',      icon: '🍺' },
  { id: 'soft',      label: 'Analcolici',      labelEn: 'Soft Drinks', labelDe: 'Alkoholfrei',labelFr: 'Sans alcool', icon: '🥤' },
  { id: 'starters',  label: 'Antipasti',       labelEn: 'Starters',    labelDe: 'Vorspeisen',labelFr: 'Entrées',     icon: '🫒' },
  { id: 'pizza',     label: 'Pizza',           labelEn: 'Pizza',       labelDe: 'Pizza',     labelFr: 'Pizza',       icon: '🍕' },
  { id: 'seafood',   label: 'Pesce',           labelEn: 'Seafood',     labelDe: 'Meeresfrüchte',labelFr: 'Poisson', icon: '🐟' },
  { id: 'meat',      label: 'Carne',           labelEn: 'Meat',        labelDe: 'Fleisch',   labelFr: 'Viande',      icon: '🥩' },
  { id: 'desserts',  label: 'Dolci',           labelEn: 'Desserts',    labelDe: 'Desserts',  labelFr: 'Desserts',    icon: '🍮' },
] as const
